In [95]:
import pandas as pd
import re

# Everest Death Data from Wikipedia

Source: https://en.wikipedia.org/wiki/List_of_people_who_died_climbing_Mount_Everest

In [96]:
#import data
ever_death_wiki = pd.read_csv("data/everest_death_wikipedia.csv")
ever_death_wiki.head()

,Unnamed: 0,Date,Age,Expedition,Nationality,Cause of death,Location,Remains status,Refs
0,Alexander Mitchell Kellas,5-Jun-21,52,1921 British Mount Everest reconnaissance expe...,United Kingdom,Heart attack,En route to base camp near the Tibetan village...,"Recovered, buried near Kampa Dzong",[9][26]
1,Unknown porter,5-Jun-21,NaN,1921 British Mount Everest reconnaissance expe...,NaN,NaN,En route to base camp near the Tibetan village...,NaN,[10]
2,Dorje,7-Jun-22,NaN,1922 British Mount Everest expedition,Nepal,Avalanche,Below North Col,NaN,[9]
3,Lhakpa,7-Jun-22,NaN,1922 British Mount Everest expedition,Nepal,Avalanche,Below North Col,NaN,[9]
4,Norbu,7-Jun-22,NaN,1922 British Mount Everest expedition,Nepal,Avalanche,Below North Col,NaN,[9]

In [97]:
ever_death_wiki.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      347 non-null    object
 1   Date            346 non-null    object
 2   Age             214 non-null    object
 3   Expedition      311 non-null    object
 4   Nationality     346 non-null    object
 5   Cause of death  336 non-null    object
 6   Location        329 non-null    object
 7   Remains status  99 non-null     object
 8   Refs            346 non-null    object
dtypes: object(9)
memory usage: 24.7+ KB

In [98]:
#how many NANs in "Location" column?
ever_death_wiki["Location"].isna().sum()

#save to no_location df
no_location = ever_death_wiki[ever_death_wiki["Location"].isna()]
no_location.head()

,Unnamed: 0,Date,Age,Expedition,Nationality,Cause of death,Location,Remains status,Refs
15,Wang Ji,11-Apr-60,NaN,Chinese Expedition Northern Slope,China,Mountain sickness,NaN,NaN,[32][33]
21,Kunga Norbu,5-Apr-70,NaN,Japanese Skiing Expedition,Nepal,Avalanche,NaN,NaN,[40]
107,Ang Pinjo,12-Dec-89,NaN,South Korean expedition,Nepal,"Altitude sickness, heart attack",NaN,NaN,[38]
108,Rafael G—mez-Menor,14-Sep-90,NaN,NaN,Spain,Avalanche,NaN,NaN,[84]
109,Ang Sona,14-Sep-90,NaN,NaN,Nepal,Avalanche,NaN,NaN,[84]

In [99]:
#remove locations = NAN
ever_death_wiki = ever_death_wiki.dropna(subset=["Location"])
ever_death_wiki.head()
#if Nationality contains NAN, replace with "Unknown"
ever_death_wiki["Nationality"] = ever_death_wiki["Nationality"].fillna("Unknown")
ever_death_wiki.head()


#create Role Column - if Nationality contains "Nepal", Role = "Nepalese", else "Climber" 
ever_death_wiki["Role"] = ever_death_wiki["Nationality"].apply(lambda x: "Nepalese" if "Nepal" in x else "Climber")


#change name of "Unnamed: 0" column to "Name"
ever_death_wiki = ever_death_wiki.rename(columns={"Unnamed: 0": "Name"})
ever_death_wiki.head()

,Name,Date,Age,Expedition,Nationality,Cause of death,Location,Remains status,Refs,Role
0,Alexander Mitchell Kellas,5-Jun-21,52,1921 British Mount Everest reconnaissance expe...,United Kingdom,Heart attack,En route to base camp near the Tibetan village...,"Recovered, buried near Kampa Dzong",[9][26],Climber
1,Unknown porter,5-Jun-21,NaN,1921 British Mount Everest reconnaissance expe...,Unknown,NaN,En route to base camp near the Tibetan village...,NaN,[10],Climber
2,Dorje,7-Jun-22,NaN,1922 British Mount Everest expedition,Nepal,Avalanche,Below North Col,NaN,[9],Nepalese
3,Lhakpa,7-Jun-22,NaN,1922 British Mount Everest expedition,Nepal,Avalanche,Below North Col,NaN,[9],Nepalese
4,Norbu,7-Jun-22,NaN,1922 British Mount Everest expedition,Nepal,Avalanche,Below North Col,NaN,[9],Nepalese

In [100]:
#sort location by most common
pd.set_option('display.max_rows', None)

ever_death_wiki["Location"].value_counts()

Location
Icefall                                                                 36
Base Camp                                                               27
Below North Col                                                         13
8600m N.E. Ridge                                                        10
Camp II                                                                  7
Near Summit                                                              7
N.E. Ridge                                                               7
Balcony                                                                  7
South Col                                                                7
6400m                                                                    7
8500m N.E. Ridge                                                         5
Camp IV                                                                  5
8700m N.E. Ridge                                                         5
South Summit                                                             5
8400m S.E. Ridge                                                         4
8000m S.W. Ridge                                                         4
5900m Icefall                                                            4
7200m W ridge                                                            4
Lhotse Face                                                              4
Hillary Step                                                             4
7800m N.E. Ridge                                                         3
8000m                                                                    3
Camp I                                                                   3
Khumbu Icefall                                                           3
8300m N.E. Ridge                                                         3
8750m S.E. Ridge                                                         3
Near Camp IV                                                             3
Base camp                                                                3
8450m S.E. Ridge                                                         2
Near Hillary Step                                                        2
7200m South Col                                                          2
8400m The Balcony                                                        2
7400m Lhotse Face                                                        2
Above Camp III                                                           2
S.E. Ridge                                                               2
North Col                                                                2
8750m N.E. Ridge                                                         2
7900m N.E. Ridge                                                         2
8400m N.E. Ridge                                                         2
En route to base camp near the Tibetan village of Kampa Dzong            2
Below the Summit                                                         2
8200m                                                                    2
7700m                                                                    2
S.W. Face                                                                2
East Rongbuk Glacier                                                     2
6900m                                                                    2
North-East Ridge (approx. 8200m)                                         2
Descending South Col Route                                               2
Above Rongbuk B.C.                                                       2
Camp III on south side                                                   1
South Col / Camp IV                                                      1
Near summit                                                              1
Base Camp North Side                                                     1
Camp IV (south side) in tent                                             1
South Col Camp                                                           1
On descent (south side)                                                  1
5600m Icefall                                                            1
Between Camp II and Camp III on descent from Camp IV (on south side)     1
7010m                                                                    1
8600m                                                                    1
Between Camps I and II in the Western Cwm                                1
Around Camp III                                                          1
6800m North Col                                                          1
Below Balcony 8300m                                                      1
8500m                                                                    1
Below Base Camp                                                          1
7900m North Face (Hornbein Couloir)                                      1
At 100m above ABC on north side (at about 6500m)                         1
5525m                                                                    1
6150m                                                                    1
8350m South Summit                                                       1
Camp III                                                                 1
The Balcony, Above Camp IV                                               1
Above Camp IV                                                            1
Descending from Camp IV                                                  1
Between Camp IV and III                                                  1
8,500m                                                                   1
'Football Field' near Icefall                                            1
Between Camp I & Camp II                                                 1
Turned back at Hillary Step (8800m)                                      1
8750m                                                                    1
The Balcony                                                              1
Base Camp following evacuation from Camp III                             1
Near South Col                                                           1
Near Balcony                                                             1
Tibet side at 8600m after summiting                                      1
Lhotse face                                                              1
8550m N.E. Ridge                                                         1
Above South Col                                                          1
Camp IV, in the tent                                                     1
N.E. Ridge 8750m                                                         1
8700m North Summit                                                       1
7850m N.E. Ridge                                                         1
4700m N.E. Ridge                                                         1
8300m North Face, Great Couloir                                          1
7400m N.E. Ridge                                                         1
8200m N.E. Ridge                                                         1
8500m West Ridge                                                         1
6800m North Col Flank                                                    1
7300m                                                                    1
7986m                                                                    1
7315m                                                                    1
7800m Lhotse Face                                                        1
8800m S.E. Ridge, Hillary Step                                           1
Hornbein Couloir, Near Summit                                            1
8600m SE Ridge                                                           1
8700m South Col                                                          1
8700m S.E. Ridge                                                         1
7200m                                                                    1
8300m S.E. Ridge                                                         1
7900m South Col                                                          1
8500m NE                                                                 1
North Face                                                               1
Lhola camp                                                               1
8350m NE                                                                 1
6238m                                                                    1
8300m W ridge                                                            1
8700m NE                                                                 1
8000m N.E.                                                               1
8800m N.E. Ridge                                                         1
8650m                                                                    1
8300m                                                                    1
7700m S.W. Face                                                          1
8650m N.E. Ridge                                                         1
Camp III, 8200m N.E. Ridge                                               1
8700m Norton Couloir                                                     1
5500m N.E. Ridge                                                         1
8200m S.E. Ridge                                                         1
5800m Icefall South                                                      1
8500m S.E. Ridge                                                         1
4600m S.E. Ridge                                                         1
8600m S.E. Ridge                                                         1
8,750m N.E. Ridge                                                        1
6900m W. Cwm                                                             1
6000m S.E. Ridge                                                         1
5500m S.E. Ridge                                                         1
Hornbein Couloir                                                         1
Below Camp III                                                           1
6770m                                                                    1
8000m South Col                                                          1
Name: count, dtype: int64

In [101]:
#Verifying "Base Camp" deaths
    #people with "Base Camp" in "Location" col of ever_death_wiki
ever_death_wiki[ever_death_wiki["Location"].str.contains("Base Camp", na=False)]

,Name,Date,Age,Expedition,Nationality,Cause of death,Location,Remains status,Refs,Role
38,Mingma ; deaf-mute Sherpa porter,Aug-75,"""Young""",1975 British Mount Everest Southwest Face expe...,Nepal,Drowned,Below Base Camp,NaN,[48],Nepalese
150,Malcolm Duff,23-Apr-97,43,British,United Kingdom,Heart attack,Base Camp,NaN,[38][94],Climber
222,Shailendra Kumar Upadhyaya,9-May-11,82,Nepal,Nepal,Altitude sickness,Base Camp,NaN,[142],Nepalese
225,Hiroaki Kino,15-Sep-11,48,Bochi Bochi Trek,Japan,Cerebral apoplexy,Base Camp,NaN,[145][146][147],Climber
227,Karsang Namgyal Sherpa,19-Apr-12,NaN,Prestige Adventures,Nepal,Altitude sickness,Base Camp,NaN,[149][150],Nepalese
228,Ramesh Gulve,20-Apr-12,33,Pune team,India,Stroke,Base Camp,NaN,[149][151],Climber
247,Mingma Tenzing Sherpa,2-Apr-14,NaN,Peak Freaks Expedition,Nepal,HAPE,Base Camp,NaN,[167],Nepalese
263,Daniel Paul Fredinburg,25-Apr-15,33,2015 Jagged Globe Everest Expedition,United States,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[16][15][17][168][169][170][171][172][173],Climber
264,Marisa Eve Girawong,25-Apr-15,28,H.G. Nuptse Expedition 2015,United States,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[169][170][171][172][173],Climber
265,Thomas Ely Taplin,25-Apr-15,61,TET Films & Photography,United States,Base Camp avalanche following the April 2015 N...,Base Camp,NaN,[170][174],Climber
266,Pemba Sherpa,25-Apr-15,19,Adventure Consultants,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][173][175][176],Nepalese
267,Dawa Tsering Sherpa,25-Apr-15,33,Adventure Consultants,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][173][176],Nepalese
268,Maila (Milan) Rai,25-Apr-15,41,Adventure Consultants,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173][175],Nepalese
269,Chhimi Dawa Sherpa,25-Apr-15,27,Adventure Consultants,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173][176],Nepalese
270,Pema Yishi (Hissi) Sherpa,25-Apr-15,33,Adventure Consultants,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173][175][176],Nepalese
271,Pasang Temba Sherpa,25-Apr-15,NaN,Tim Mosedale Everest Expedition (or H.G. Evere...,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173][177],Nepalese
272,Krishna Kumar Rai,25-Apr-15,NaN,Tim Mosedale Everest Expedition (or H.G. Evere...,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173][177],Nepalese
273,Tenzing (Tengien) Bhote,25-Apr-15,NaN,Tim Mosedale Everest Expedition (or H.G. Evere...,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173][178],Nepalese
274,Renu Fotedar,25-Apr-15,49,First Chinese Women Everest Expedition,Australia,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][177][173],Climber
276,Lhakpa Chhiring Sherpa,25-Apr-15,33,First Chinese Women Everest Expedition,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173],Nepalese
277,Vinh B Truong,25-Apr-15,48,Trekker,United States,Base Camp avalanche following the April 2015 N...,Base Camp,NaN,[170][171],Climber
279,Shiva Kumar Shrestha,25-Apr-15,25,Step Up Campaign Everest,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,Recovered,[171][172][173],Nepalese
280,Unnamed,25-Apr-15,NaN,NaN,Unknown,Base Camp avalanche following the April 2015 N...,Base Camp,NaN,[179],Climber
281,Unnamed,25-Apr-15,NaN,NaN,Unknown,Base Camp avalanche following the April 2015 N...,Base Camp,NaN,[179],Climber
282,Jangbu Sherpa,1-May-15,NaN,Adventure Consultants,Nepal,Base Camp avalanche following the April 2015 N...,Base Camp,"Evacuated, succumbed to injuries in hospital",[171][175][176],Nepalese
283,Charles MacAdams,11-May-16,62,NaN,Canada,Cardiac event,Base Camp North Side,Recovered,[180][181][182],Climber
291,Minn Bahadur Serchan,5-May-17,85,NaN,Nepal,Heart attack,Base Camp,Recovered,[195][196],Nepalese
308,Dhruba Bista,24-May-19,NaN,Himalayan Ecstasy (Ski) Treks,Nepal,Exhaustion and altitude sickness,Base Camp following evacuation from Camp III,Recovered,[229],Nepalese
325,Suzanne Leopoldina Jesus,18-May-23,59,Glacier Himalaya Treks,India,Illness,Base Camp,"Evacuated, died in hospital",[251],Climber
337,Marista Rita Sinaga,28-Apr-24,NaN,Mount Adventures,Indonesia,Unknown,Base Camp,"Evacuated, died in hospital",[272][273],Climber

In [131]:
ever_death_cleaned_locations = ever_death_wiki.copy()

#remove commas from "Location" column
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].str.replace(",", "")

#all deaths that mention "Balcony" in the location will be categorized as "Balcony"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Balcony" if re.search("Balcony", x) else x)
#all deaths mentioning Hillary Step will be categorized as "Hillary Step"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Hillary Step" if re.search("Hillary Step", x) else x)
#Hornbein Couloir will be categorized as "Hornbein Couloir"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Hornbein Couloir" if re.search("Hornbein Couloir", x) else x)
#all icefall becomes Khumbu Icefall
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Khumbu Icefall" if re.search("Icefall", x) else x)


#Routes should be organized from bottom to top -> need to parse out North Route, South Route, and West Ridge route
    #because some locations are names and some are elevations, will add evelations to front of location name

#if "Base Camp North Side" in location, add "6490m" to front of location name
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "6490m " + x if re.search("Base Camp North Side", x) else x)
# if "North Col" in location, add "7000m" to front of location name
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "7000m " + x if re.search("North Col", x) else x)
# if "Karl" in "Name", change location to 6400m Below North Col
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations.apply(lambda row: "6400m Below North Col" if re.search("Karl", row["Name"]) else row["Location"], axis=1)
#if only 6400m in location, change to 6400m W Ridge
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "6400m W Ridge" if re.search("6400m", x) and not re.search("North Col", x) else x)
#if "Above" or "Descending" and "South Col" in location, change to "8000m Above South Col"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations.apply(lambda row: "8000m Above South Col" if (re.search("Above", row["Location"]) or re.search("Descending", row["Location"])) and re.search("South Col", row["Location"]) else row["Location"], axis=1)
#if "Above South Col" and no numeric characters in location, change to "8000m Above South Col"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations.apply(lambda row: "8000m Above South Col" if re.search("Above South Col", row["Location"]) and not re.search("\d", row["Location"]) else row["Location"], axis=1)
#locations where "South Col" appears with no numeric characters, add 7900m to front of location name
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations.apply(lambda row: "7900m " + row["Location"] if re.search("South Col", row["Location"]) and not re.search("\d", row["Location"]) else row["Location"], axis=1)
#If Marty Hoey is in "Name", change location to "8000m N.E. Ridge"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations.apply(lambda row: "8000m N.E. Ridge" if re.search("Marty Hoey", row["Name"]) else row["Location"], axis=1)
#if only "8000m" in location, change to "8000m W Ridge"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "8000m W Ridge" if re.search("8000m", x) and not re.search("South Col", x) and not re.search("N.E. Ridge", x) else x)
#if "Lhotse Face" or "Lhoste face" in location, change to "7400m Lhotse Face"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "7400m Lhotse Face" if re.search("Lhotse Face", x) or re.search("Lhotse face", x) else x)
#if only "Near Camp IV" in location, change to "Camp IV"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Camp IV" if re.search("Near Camp IV", x) else x)
#if "Camp IV (south side) in tent" or "Camp IV in the tent" in location, change to "Camp IV"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Camp IV" if re.search("Camp IV \(south side\) in tent", x) or re.search("Camp IV in the tent", x) else x)
#if only "Base camp" case senitive, change to "Base Camp"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Base Camp" if re.search("Base camp", x) else x)
#if contains "Base Camp North Side" or "Rongbuk", chang to "Base Camp North Side"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Base Camp North Side" if re.search("Base Camp North Side", x) or re.search("Rongbuk", x) else x)
#if "NE" in location, change that text to "N.E." same with SE to S.E.
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: re.sub(r"\bNE\b", "N.E.", x))
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: re.sub(r"\bSE\b", "S.E.", x))
#if "S.W. Face" in location and no numeric, change to "7700m S.W. Face"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations.apply(lambda row: "7700m S.W. Face" if re.search("S.W. Face", row["Location"]) and not re.search("\d", row["Location"]) else row["Location"], axis=1)
#if "W ridge" or "W Ridge" in location, repalce with "West Ridge"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: re.sub(r"W Ridge|W ridge", "West Ridge", x))
#"Near summit" and "Below the Summit" becomes "Near Summit"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "Near Summit" if re.search("Near summit", x) or re.search("Below the Summit", x) else x)
#if "6900m" appears, change to "6900m W. Cwm"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "6900m W. Cwm" if re.search("6900m", x) else x)
#"North-East Ridge (approx. 8200m)" to "8200m N.E. Ridge"
ever_death_cleaned_locations["Location"] = ever_death_cleaned_locations["Location"].apply(lambda x: "8200m N.E. Ridge" if re.search("North-East Ridge", x) and re.search("8200m", x) else x)


ever_death_cleaned_locations["Location"].value_counts()

Location
Khumbu Icefall                                                          46
Base Camp                                                               30
7000m Below North Col                                                   13
Balcony                                                                 13
Near Summit                                                             10
Camp IV                                                                 10
8600m N.E. Ridge                                                        10
7400m Lhotse Face                                                        8
7900m South Col                                                          8
Hillary Step                                                             8
8000m West Ridge                                                         7
N.E. Ridge                                                               7
Camp II                                                                  7
6400m West Ridge                                                         6
South Summit                                                             5
8500m N.E. Ridge                                                         5
Base Camp North Side                                                     5
8700m N.E. Ridge                                                         5
8400m S.E. Ridge                                                         4
7200m West Ridge                                                         4
8000m Above South Col                                                    3
8200m N.E. Ridge                                                         3
8750m N.E. Ridge                                                         3
7800m N.E. Ridge                                                         3
8750m S.E. Ridge                                                         3
Hornbein Couloir                                                         3
Camp I                                                                   3
8300m N.E. Ridge                                                         3
7700m S.W. Face                                                          3
6900m W. Cwm                                                             3
7000m North Col                                                          2
7900m N.E. Ridge                                                         2
S.E. Ridge                                                               2
8400m N.E. Ridge                                                         2
Above Camp III                                                           2
7200m South Col                                                          2
8450m S.E. Ridge                                                         2
En route to base camp near the Tibetan village of Kampa Dzong            2
8600m S.E. Ridge                                                         2
7700m                                                                    2
8500m                                                                    2
8200m                                                                    2
8350m N.E.                                                               1
Below Base Camp                                                          1
Camp III on south side                                                   1
At 100m above ABC on north side (at about 6500m)                         1
Between Camps I and II in the Western Cwm                                1
8000m N.E. Ridge                                                         1
On descent (south side)                                                  1
7010m                                                                    1
8600m                                                                    1
7000m 6800m North Col                                                    1
8700m North Summit                                                       1
N.E. Ridge 8750m                                                         1
4700m N.E. Ridge                                                         1
Between Camp II and Camp III on descent from Camp IV (on south side)     1
6150m                                                                    1
7900m South Col Camp                                                     1
8800m N.E. Ridge                                                         1
7900m South Col / Camp IV                                                1
Around Camp III                                                          1
8550m N.E. Ridge                                                         1
5525m                                                                    1
Tibet side at 8600m after summiting                                      1
7900m Near South Col                                                     1
Base Camp following evacuation from Camp III                             1
8750m                                                                    1
8350m South Summit                                                       1
Between Camp I & Camp II                                                 1
Between Camp IV and III                                                  1
Descending from Camp IV                                                  1
Above Camp IV                                                            1
8000m South Col                                                          1
8300m                                                                    1
8650m                                                                    1
8700m N.E.                                                               1
7850m N.E. Ridge                                                         1
6400m Below North Col                                                    1
North Face                                                               1
8500m N.E.                                                               1
Lhola camp                                                               1
8300m S.E. Ridge                                                         1
8700m S.E. Ridge                                                         1
8700m South Col                                                          1
7200m                                                                    1
8300m North Face Great Couloir                                           1
7315m                                                                    1
7986m                                                                    1
7000m 6800m North Col Flank                                              1
7300m                                                                    1
7400m N.E. Ridge                                                         1
8500m West Ridge                                                         1
6238m                                                                    1
8500m S.E. Ridge                                                         1
8300m West Ridge                                                         1
6770m                                                                    1
Below Camp III                                                           1
5500m S.E. Ridge                                                         1
6000m S.E. Ridge                                                         1
4600m S.E. Ridge                                                         1
8200m S.E. Ridge                                                         1
5500m N.E. Ridge                                                         1
8700m Norton Couloir                                                     1
Camp III 8200m N.E. Ridge                                                1
8650m N.E. Ridge                                                         1
Camp III                                                                 1
Name: count, dtype: int64

In [132]:
#adding a new "Route" column to categorize locations into North Route, South Route, and West Ridge
def categorize_route(location):
    #if "North" or "N.E." in location, return "North"
    if re.search("North", location) or re.search("N\.E\.", location) or re.search("Hillary Step", location) or re.search("Hornbein Couloir", location) or re.search("Norton Couloir", location) or re.search("north", location) or re.search("Tibet", location):
        return "North"
    #if "W." or "S.W." or "Lhola camp" or "West Ridge" in location, return "West Ridge" 
    elif re.search("S\.W\.", location) or re.search("Lhola camp", location) or re.search("West Ridge", location):
        return "West Ridge"
    #if "South", "S.E.", "Kumbu Icefall", "Base Camp" with nothing else, return "South"
    #added balcony and Lhotse
    elif re.search("South", location) or re.search("Cwm", location) or re.search("south", location) or re.search("Lhotse", location) or re.search("Balcony", location) or re.search("S\.E\.", location) or re.search("Khumbu Icefall", location) or (re.search("Base Camp", location) and not re.search("North", location)):
        return "South"
    #else return "Other"
    else:
        return "Other"
    
ever_death_cleaned_locations["Route"] = ever_death_cleaned_locations["Location"].apply(categorize_route)

#if in "Other" and "Camp" in location, change route to "South"
ever_death_cleaned_locations["Route"] = ever_death_cleaned_locations.apply(lambda row: "South" if row["Route"] == "Other" and re.search("Camp", row["Location"]) else row["Route"], axis=1)

In [133]:
ever_death_cleaned_locations.groupby("Route")["Location"].value_counts()

Route       Location
North       7000m Below North Col                                                   13
            8600m N.E. Ridge                                                        10
            Hillary Step                                                             8
            N.E. Ridge                                                               7
            8500m N.E. Ridge                                                         5
            8700m N.E. Ridge                                                         5
            Base Camp North Side                                                     5
            7800m N.E. Ridge                                                         3
            8200m N.E. Ridge                                                         3
            8300m N.E. Ridge                                                         3
            8750m N.E. Ridge                                                         3
            Hornbein Couloir                                                         3
            7000m North Col                                                          2
            7900m N.E. Ridge                                                         2
            8400m N.E. Ridge                                                         2
            En route to base camp near the Tibetan village of Kampa Dzong            2
            4700m N.E. Ridge                                                         1
            5500m N.E. Ridge                                                         1
            6400m Below North Col                                                    1
            7000m 6800m North Col                                                    1
            7000m 6800m North Col Flank                                              1
            7400m N.E. Ridge                                                         1
            7850m N.E. Ridge                                                         1
            8000m N.E. Ridge                                                         1
            8300m North Face Great Couloir                                           1
            8350m N.E.                                                               1
            8500m N.E.                                                               1
            8550m N.E. Ridge                                                         1
            8650m N.E. Ridge                                                         1
            8700m N.E.                                                               1
            8700m North Summit                                                       1
            8700m Norton Couloir                                                     1
            8800m N.E. Ridge                                                         1
            At 100m above ABC on north side (at about 6500m)                         1
            Camp III 8200m N.E. Ridge                                                1
            N.E. Ridge 8750m                                                         1
            North Face                                                               1
            Tibet side at 8600m after summiting                                      1
Other       Near Summit                                                             10
            7700m                                                                    2
            8200m                                                                    2
            8500m                                                                    2
            5525m                                                                    1
            6150m                                                                    1
            6238m                                                                    1
            6770m                                                                    1
            7010m                                                                    1
            7200m                                                                    1
            7300m                                                                    1
            7315m                                                                    1
            7986m                                                                    1
            8300m                                                                    1
            8600m                                                                    1
            8650m                                                                    1
            8750m                                                                    1
South       Khumbu Icefall                                                          46
            Base Camp                                                               30
            Balcony                                                                 13
            Camp IV                                                                 10
            7400m Lhotse Face                                                        8
            7900m South Col                                                          8
            Camp II                                                                  7
            South Summit                                                             5
            8400m S.E. Ridge                                                         4
            6900m W. Cwm                                                             3
            8000m Above South Col                                                    3
            8750m S.E. Ridge                                                         3
            Camp I                                                                   3
            7200m South Col                                                          2
            8450m S.E. Ridge                                                         2
            8600m S.E. Ridge                                                         2
            Above Camp III                                                           2
            S.E. Ridge                                                               2
            4600m S.E. Ridge                                                         1
            5500m S.E. Ridge                                                         1
            6000m S.E. Ridge                                                         1
            7900m Near South Col                                                     1
            7900m South Col / Camp IV                                                1
            7900m South Col Camp                                                     1
            8000m South Col                                                          1
            8200m S.E. Ridge                                                         1
            8300m S.E. Ridge                                                         1
            8350m South Summit                                                       1
            8500m S.E. Ridge                                                         1
            8700m S.E. Ridge                                                         1
            8700m South Col                                                          1
            Above Camp IV                                                            1
            Around Camp III                                                          1
            Base Camp following evacuation from Camp III                             1
            Below Base Camp                                                          1
            Below Camp III                                                           1
            Between Camp I & Camp II                                                 1
            Between Camp II and Camp III on descent from Camp IV (on south side)     1
            Between Camp IV and III                                                  1
            Between Camps I and II in the Western Cwm                                1
            Camp III                                                                 1
            Camp III on south side                                                   1
            Descending from Camp IV                                                  1
            On descent (south side)                                                  1
West Ridge  8000m West Ridge                                                         7
            6400m West Ridge                                                         6
            7200m West Ridge                                                         4
            7700m S.W. Face                                                          3
            8300m West Ridge                                                         1
            8500m West Ridge                                                         1
            Lhola camp                                                               1
Name: count, dtype: int64

In [ ]:
#locations where "South Col" appears with no numeric characters
ever_death_cleaned_locations[ever_death_cleaned_locations["Location"].str.contains("South Col") & ~ever_death_cleaned_locations["Location"].str.contains("\d")]["Location"].value_counts()

In [ ]:
#look at all "Location" that start with a non numeric character
ever_death_cleaned_locations[~ever_death_cleaned_locations["Location"].str.match("^\d")]["Location"].value_counts()

In [ ]:
ever_death_cleaned_locations["Location"].value_counts()

#locations grouped by nationality
ever_death_cleaned_locations.groupby("Role")["Location"].value_counts()

## Everest Expedition Data for Routes

In [ ]:
routes = pd.read_csv("data/EverestExpeditions_HimalayanDatabase.csv")
routes.head()

In [ ]:
routes.info()

In [ ]:
routes.iloc[3,7]

In [ ]:
#column names?
routes.columns
#remove spaces from column names
routes.columns = routes.columns.str.replace(" ", "")
routes.columns
#for "Route(s)", replace / with AND-OR
routes["Route(s)"] = routes["Route(s)"].str.replace("/", " AND-OR ")

In [ ]:
#drop rows where "Dead" is nan
routes = routes.dropna(subset=["Dead"])
routes.head(10)

In [ ]:
#count number of instances of each unique route in "Route(s)"
routes["Route(s)"].value_counts()

In [ ]:
#number of unique routes and number of deaths for each route
route_deaths = routes.groupby("Route(s)")["Dead"].sum()
route_deaths.sort_values(ascending=False)

In [ ]:
#total deaths
total_deaths = routes["Dead"].sum()
print(total_deaths)